version: '3.9'

services:

  web-desktopcont1:
    build: ./server1.com
    container_name: web-desktopcont1
    restart: always
    ports:
      - "5001:3000"

  web-desktopcont2:
    build: ./server1.com
    container_name: web-desktopcont2
    ports:
      - "5002:3000"

  web-mobilecont1:
    build: ./server2.com
    container_name: web-mobilecont1
    ports:
      - "5003:3000"


  web-mobilecont2:
    build: ./server2.com
    container_name: web-mobilecont2
    ports:
      - "5004:3000"
