version: '3.8'

services:

  web-desktopcont1:
    build: ./server1.com
    container_name: web-desktopcont1
    restart: always
    volumes:
      - /var/lib/docker/volumes/server1:/srv/http
    ports:
      - "8081:80"

  web-desktopcont2:
    build: ./server1.com
    container_name: web-desktopcont2
    volumes:
      - /var/lib/docker/volumes/server1:/srv/http
    ports:
      - "8082:80"

  web-mobilecont1:
    build: ./server2.com
    container_name: web-mobilecont1
    volumes:
      - /var/lib/docker/volumes/server2:/srv/http
    ports:
      - "8083:80"


  web-mobilecont2:
    build: ./server2.com
    container_name: web-mobilecont2
    volumes:
      - /var/lib/docker/volumes/server2:/srv/http
    ports:
      - "8084:80"
